#!/bin/bash

FILE=/etc/openvpn/$1.conf
if [ -f "$FILE" ]; then
    sudo ./scripts/stop
    sudo openvpn --config /etc/openvpn/$1.conf --daemon
else 
    echo "server configuration $1 does not exist."
fi

