#!/bin/bash

FILE=/etc/openvpn/$1.conf
if [ -f "$FILE" ]; then
    /code/scripts/stopvpn
    /code/scripts/stopwg

    sudo openvpn --config /etc/openvpn/$1.conf --daemon
else 
    echo "server configuration $1 does not exist."
fi

